export async function getServerSideProps({ res }) {
  const base = process.env.NEXT_PUBLIC_URL || 'https://gamingguiden.vercel.app';
  const pages = [{"path":"","priority":"1.0","changefreq":"daily"},{"path":"/om-oss","priority":"0.5","changefreq":"monthly"},{"path":"/kontakt","priority":"0.4","changefreq":"monthly"},{"path":"/integritetspolicy","priority":"0.3","changefreq":"yearly"},{"path":"/konsol","priority":"0.8","changefreq":"weekly"},{"path":"/gaming-headset","priority":"0.8","changefreq":"weekly"},{"path":"/gaming-stol","priority":"0.8","changefreq":"weekly"},{"path":"/gaming-mus","priority":"0.8","changefreq":"weekly"},{"path":"/spelkontroll","priority":"0.8","changefreq":"weekly"},{"path":"/jamfor/steelseries-arctis-nova-pro-vs-razer-blackshark-v2-pro","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/steelseries-arctis-nova-pro-vs-hyperx-cloud-alpha-wireless","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/steelseries-arctis-nova-pro-vs-logitech-g-pro-x-wireless","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/steelseries-arctis-nova-pro-vs-corsair-virtuoso-rgb-wireless-xt","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/steelseries-arctis-nova-pro-vs-astro-a50-wireless","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/steelseries-arctis-nova-pro-vs-turtle-beach-stealth-700-gen-2","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/razer-blackshark-v2-pro-vs-hyperx-cloud-alpha-wireless","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/razer-blackshark-v2-pro-vs-logitech-g-pro-x-wireless","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/razer-blackshark-v2-pro-vs-corsair-virtuoso-rgb-wireless-xt","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/razer-blackshark-v2-pro-vs-astro-a50-wireless","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/razer-blackshark-v2-pro-vs-turtle-beach-stealth-700-gen-2","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/hyperx-cloud-alpha-wireless-vs-logitech-g-pro-x-wireless","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/hyperx-cloud-alpha-wireless-vs-corsair-virtuoso-rgb-wireless-xt","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/hyperx-cloud-alpha-wireless-vs-astro-a50-wireless","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/hyperx-cloud-alpha-wireless-vs-turtle-beach-stealth-700-gen-2","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/logitech-g-pro-x-wireless-vs-corsair-virtuoso-rgb-wireless-xt","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/logitech-g-pro-x-wireless-vs-astro-a50-wireless","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/logitech-g-pro-x-wireless-vs-turtle-beach-stealth-700-gen-2","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/corsair-virtuoso-rgb-wireless-xt-vs-astro-a50-wireless","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/corsair-virtuoso-rgb-wireless-xt-vs-turtle-beach-stealth-700-gen-2","priority":"0.7","changefreq":"weekly"},{"path":"/jamfor/astro-a50-wireless-vs-turtle-beach-stealth-700-gen-2","priority":"0.7","changefreq":"weekly"}];
  const xml = '<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">' +
    pages.map(function(p) { return '<url><loc>'+base+p.path+'</loc><lastmod>2026-06-24</lastmod><changefreq>'+p.changefreq+'</changefreq><priority>'+p.priority+'</priority></url>'; }).join('') +
    '</urlset>';
  res.setHeader('Content-Type', 'application/xml');
  res.setHeader('Cache-Control', 's-maxage=86400, stale-while-revalidate');
  res.write(xml); res.end();
  return { props: {} };
}
export default function Sitemap() { return null; }